### ISSUE TITLE
Github Page Template

### ISSUE THREAD

**Issue by Zilinghan** [gpauloski/gpauloski.github.io#159]
Hi Greg,

I am a user of ProxyStore, and through it, I came across your personal GitHub page. I found it to be very clean and well-organized. Would it be alright if I used it as a template for my own personal GitHub page? Thank you!

**Comment by gpauloski** [comment]
Hi @Zilinghan! Yes, you are welcome to fork/use this template.

If you have any questions about how things work, feel free to open another issue!
